### ISSUE TITLE
Cannot import earthkit.data when earthkit is also installed

### ISSUE THREAD

**Issue by sandorkertesz** [ecmwf/earthkit-data#74]
### What happened?

This happens on the ECMWF ATOS supercomputer in a conda environment. If both the `earthkit-data` and `earthkit` packages are installed from their git repos with `pip install . -e` `earthkit.data` cannot be imported:

```
>>> import earthkit.data
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File ".../git/earthkit/earthkit/__init__.py", line 10, in <module>
    import earthkit.data as data
ModuleNotFoundError: No module named 'earthkit.data'
```

Python version is: 3.8.12

### What are the steps to reproduce the bug?

See above

### Version

develop

### Platform (OS and architecture)

Linux

**Comment by sandorkertesz** [comment]
It seems that fixing #88 solved this problem too.
